#!/bin/sh

WIFI_STATUS=$(cat /sys/class/net/w*/operstate)
ETHERNET_STATUS=$(cat /sys/class/net/e*/operstate)

if [ "$WIFI_STATUS" = "up" ]; then
	SSID="$(iwgetid -r)"
	echo "󰖩 $SSID"
elif [ "$ETHERNET_STATUS" = "up" ]; then
	echo ""
else
	if rfkill -o TYPE,SOFT -nr | grep -q "wlan blocked"; then
		echo "󱚼"
	else
		echo "󰖪"
	fi
fi
